/**
 * Created by Benzo Media.
 * http://www.benzomedia.com
 * User: Oren Reuveni
 * Date: 25/07/2016
 * Time: 13:38
 */



export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const REQUEST_USER = "REQUEST_USER"
export const RECEIVE_USER = "RECEIVE_USER"
export const RECEIVE_USER_FAILURE = "RECEIVE_USER_FAILURE"
export const TOGGLE_MESSAGE = "TOGGLE_MESSAGE"
export const TOGGLE_USER_EDIT_MODE = "TOGGLE_USER_EDIT_MODE"
export const SET_PREVIEW_IMAGE = "SET_PREVIEW_IMAGE"
export const REQUEST_UPLOAD_IMAGE = "REQUEST_UPLOAD_IMAGE"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE"
export const REQUEST_UPDATE_USER_PROFILE = "REQUEST_UPDATE_USER_PROFILE"
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS"
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE"
export const REQUEST_RESET_PASSWORD_REQUEST = "REQUEST_RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS"
export const RESET_PASSWORD_REQUEST_FAILURE = "RESET_PASSWORD_REQUEST_FAILURE"
export const REQUEST_RESET_PASSWORD = "REQUEST_RESET_PASSWORD"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"
export const REQUEST_SIGNUP = "REQUEST_SIGNUP"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"
export const SET_ERROR = "SET_ERROR"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const SET_ROLE = "SET_ROLE"
export const REQUEST_CHECK_USERNAME = "REQUEST_CHECK_USERNAME"
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS"
export const CHECK_USERNAME_FAILURE = "CHECK_USERNAME_FAILURE"
export const REQUEST_GET_ACTORS = "REQUEST_GET_ACTORS"
export const GET_ACTORS_SUCCESS = "GET_ACTORS_SUCCESS"
export const GET_ACTORS_FAILURE = "GET_ACTORS_FAILURE"
export const REQUEST_UPDATE_USER_IMAGES = "REQUEST_UPDATE_USER_IMAGES"
export const UPDATE_USER_IMAGES_SUCCESS = "UPDATE_USER_IMAGES_SUCCESS"
export const UPDATE_USER_IMAGES_FAILURE = "UPDATE_USER_IMAGES_FAILURE"




